import React from 'react';
import { StickyNavigation } from '@/components/blocks/sticky-navigation';
import { CMSFooter } from '@/components/blocks/cms-footer';
import { getNavigationData, getFooterData } from '@/lib/navigation';

export default async function PrivacyPolicyPage() {
  const navigationData = await getNavigationData();
  const footerData = await getFooterData();

  return (
    <div className="min-h-screen bg-surface-light">
      <StickyNavigation navigationData={navigationData} />
      
      <main className="container-outer pt-32 pb-spacing-section">
        <div className="container-inner">
          <div className="w-text mx-auto">
            {/* Header */}
            <div className="mb-12">
              <h1 className="title-6xl text-content-primary mb-6">
                Privacy Policy
              </h1>
              <p className="text-lg text-content-muted">
                Last updated: {new Date().toLocaleDateString('en-GB')}
              </p>
            </div>

            {/* Content */}
            <div className="prose max-w-none">
              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">Who we are</h2>
                <p className="text-content-muted mb-4">
                  Our website address is: <a href="https://www.r3.agency" className="text-content-brand hover:underline">https://www.r3.agency</a>
                </p>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">1. Introduction</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>1.1.</strong> We are committed to safeguarding the privacy of our website visitors, service users, individual customers, and customer personnel.
                  </p>
                  
                  <p>
                    <strong>1.2.</strong> This policy applies where we are acting as a data controller with respect to the personal data of such persons; in other words, where we determine the purposes and means of the processing of that personal data.
                  </p>
                  
                  <p>
                    <strong>1.3.</strong> Our website incorporates privacy controls which affect how we will process your personal data. By using the privacy controls, you can specify whether you would like to receive direct marketing communications and limit the collection, sharing and publication of your personal data. You can access the cookie banner via any page of the website.
                  </p>
                  
                  <p>
                    <strong>1.4.</strong> We use cookies on our website. Insofar as those cookies are not strictly necessary for the provision of our website and services, we will ask you to consent to our use of cookies when you first visit our website.
                  </p>
                  
                  <p>
                    <strong>1.5.</strong> In this policy, &quot;we&quot;, &quot;us&quot; and &quot;our&quot; refers to R3 Group Ltd. For more information about us, see Section 13.
                  </p>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">2. The personal data that we collect</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>2.1.</strong> In this Section 2 we have set out the general categories of personal data that we process and, in the case of personal data that we did not obtain directly from you, information about the source and specific categories of that data.
                  </p>
                  
                  <p>
                    <strong>2.2.</strong> We may process data enabling us to get in touch with you (&quot;contact data&quot;). The contact data may include your name, email address, telephone number, postal address, job title, and company name. The source of the contact data is you.
                  </p>
                  
                  <p>
                    <strong>2.3.</strong> We may process your website user account data (&quot;account data&quot;). The account data may include your account identifier, name, email address, business name, account settings, and marketing preferences. The primary source of the account data is you, although some elements of the account data may be generated by our website.
                  </p>
                  
                  <p>
                    <strong>2.4.</strong> We may process information relating to transactions, including purchases of goods and/or services from us (&quot;transaction data&quot;). The transaction data may include your name, your contact details, your payment details, and the transaction details. The source of the transaction data is you and/or our payment services provider.
                  </p>
                  
                  <p>
                    <strong>2.5.</strong> We may process information contained in or relating to any communication that you send to us or that we send to you (&quot;communication data&quot;). The communication data may include the communication content and metadata associated with the communication.
                  </p>
                  
                  <p>
                    <strong>2.6.</strong> We may process data about your use of our website and services (&quot;usage data&quot;). The usage data may include your IP address, geographical location, browser type and version, operating system, referral source, length of visit, page views and website navigation paths, as well as information about the timing, frequency and pattern of your service use. The source of the usage data is our analytics tracking systems.
                  </p>
                  
                  <p>
                    <strong>2.7.</strong> We may process server access logs (&quot;access log data&quot;). The access log data consists of a temporary text file containing a list of pages visited, along with the IP address and user agent of the visitor. This data cannot identify you personally and is automatically deleted after a few hours when it reaches a certain size. The source of this data is our web server.
                  </p>
                  
                  <p>
                    <strong>2.8.</strong> We may process information that you provide to us for the purpose of subscribing to our email notifications, newsletters, and/or marketing materials (&quot;notification data&quot;). The notification data may include your name, email address, and marketing preferences.
                  </p>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">3. Purposes of processing and legal bases</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>3.1.</strong> In this Section 3, we have set out the purposes for which we may process personal data and the legal bases of the processing.
                  </p>
                  
                  <p>
                    <strong>3.2.</strong> <strong>Operations</strong> – We may process your personal data for the purposes of operating our website, providing our marketing and technology services, delivering our services, ensuring the security of our website and services, maintaining back-ups of our databases, and communicating with you. The legal basis for this processing is our legitimate interests, namely the proper administration of our website, services and business.
                  </p>
                  
                  <p>
                    <strong>3.3.</strong> <strong>Publications</strong> – We may process account data for the purposes of publishing such data on our website and elsewhere through our services in accordance with your express instructions. The legal basis for this processing is our legitimate interests, namely the publication of content in the ordinary course of our operations.
                  </p>
                  
                  <p>
                    <strong>3.4.</strong> <strong>Relationships and communications</strong> – We may process contact data, account data, transaction data and/or communication data for the purposes of managing our relationships, communicating with you (excluding communicating for the purposes of direct marketing) by email, SMS, post, and/or telephone, providing support services and complaint handling. The legal basis for this processing is our legitimate interests, namely communications with our website visitors, service users, individual customers and customer personnel, the maintenance of relationships, and the proper administration of our website, services, and business.
                  </p>
                  
                  <p>
                    <strong>3.5.</strong> <strong>Direct marketing</strong> – We may process contact data, account data, notification data and/or transaction data for the purposes of creating, targeting and sending direct marketing communications by email, SMS or post and making contact by telephone for marketing-related purposes. The legal basis for this processing is consent OR our legitimate interests, namely promoting our business and communicating marketing messages and offers to our website visitors and service users.
                  </p>
                  
                  <p>
                    <strong>3.6.</strong> <strong>Research and analysis</strong> – We may process usage data and/or transaction data for the purposes of researching and analysing the use of our website and services, as well as researching and analysing other interactions with our business. The legal basis for this processing is our legitimate interests, namely monitoring, supporting, improving, and securing our website, services and business generally.
                  </p>
                  
                  <p>
                    <strong>3.7.</strong> <strong>Record keeping</strong> – We may process your personal data for the purposes of creating and maintaining our databases, back-up copies of our databases and our business records generally. The legal basis for this processing is our legitimate interests, namely ensuring that we have access to all the information we need to properly and efficiently run our business in accordance with this policy.
                  </p>
                  
                  <p>
                    <strong>3.8.</strong> <strong>Security</strong> – We may process your personal data for the purposes of security and the prevention of fraud and other criminal activity. The legal basis of this processing is our legitimate interests, namely the protection of our website, services and business, and the protection of others.
                  </p>
                  
                  <p>
                    <strong>3.9.</strong> <strong>Technical operations</strong> – We may process access log data for the purposes of monitoring website functionality, identifying bugs, and maintaining the technical operation of our website. The legal basis for this processing is our legitimate interests, namely ensuring the proper functioning and security of our website.
                  </p>
                  
                  <p>
                    <strong>3.10.</strong> <strong>Insurance and risk management</strong> – We may process your personal data where necessary for the purposes of obtaining or maintaining insurance coverage, managing risks and/or obtaining professional advice. The legal basis for this processing is our legitimate interests, namely the proper protection of our business against risks.
                  </p>
                  
                  <p>
                    <strong>3.11.</strong> <strong>Legal claims</strong> – We may process your personal data where necessary for the establishment, exercise or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure. The legal basis for this processing is our legitimate interests, namely the protection and assertion of our legal rights, your legal rights and the legal rights of others.
                  </p>
                  
                  <p>
                    <strong>3.12.</strong> <strong>Legal compliance and vital interests</strong> – We may also process your personal data where such processing is necessary for compliance with a legal obligation to which we are subject or in order to protect your vital interests or the vital interests of another natural person.
                  </p>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">4. Providing your personal data to others</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>4.1.</strong> We may disclose your personal data to our insurers and/or professional advisers insofar as reasonably necessary for the purposes of obtaining or maintaining insurance coverage, managing risks, obtaining professional advice.
                  </p>
                  
                  <p>
                    <strong>4.2.</strong> Your personal data held in our website database will be stored on the servers of our hosting services providers.
                  </p>
                  
                  <p>
                    <strong>4.3.</strong> We may disclose your personal data to our suppliers or subcontractors insofar as reasonably necessary for the provision of our marketing and technology services.
                  </p>
                  
                  <p>
                    <strong>4.4.</strong> Financial transactions relating to our website and services may be handled by our payment services providers. We will share transaction data with our payment services providers only to the extent necessary for the purposes of processing your payments, refunding such payments, and dealing with complaints and queries relating to such payments and refunds.
                  </p>
                  
                  <p>
                    <strong>4.5.</strong> In addition to the specific disclosures of personal data set out in this Section 4, we may disclose your personal data where such disclosure is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person. We may also disclose your personal data where such disclosure is necessary for the establishment, exercise, or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure.
                  </p>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">5. International transfers of your personal data</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>5.1.</strong> In this Section 5, we provide information about the circumstances in which your personal data may be transferred to a third country under UK and/or EU data protection law.
                  </p>
                  
                  <p>
                    <strong>5.2.</strong> We may transfer your personal data from the European Economic Area (EEA) to the UK and process that personal data in the UK for the purposes set out in this policy, and may permit our suppliers and subcontractors to do so, during any period with respect to which the UK is not treated as a third country under EU data protection law or benefits from an adequacy decision under EU data protection law; and we may transfer your personal data from the UK to the EEA and process that personal data in the EEA for the purposes set out in this policy, and may permit our suppliers and subcontractors to do so, during any period with respect to which EEA states are not treated as third countries under UK data protection law or benefit from adequacy regulations under UK data protection law.
                  </p>
                  
                  <p>
                    <strong>5.3.</strong> The hosting facilities for our website are situated in the United Kingdom and utilise cloud CDN services. The competent data protection authorities have made an adequacy determination with respect to the data protection laws of these locations. Where cloud CDN services are used, transfers will be protected by appropriate safeguards, namely the use of standard contractual clauses adopted by the UK Information Commissioner&apos;s Office.
                  </p>
                  
                  <p>
                    <strong>5.4.</strong> You acknowledge that personal data that you submit for publication through our website or services may be available, via the internet, around the world. We cannot prevent the use (or misuse) of such personal data by others.
                  </p>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">6. Retaining and deleting personal data</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>6.1.</strong> This Section 6 sets out our data retention policies and procedures, which are designed to help ensure that we comply with our legal obligations in relation to the retention and deletion of personal data.
                  </p>
                  
                  <p>
                    <strong>6.2.</strong> Personal data that we process for any purpose or purposes shall not be kept for longer than is necessary for that purpose or those purposes.
                  </p>
                  
                  <p>
                    <strong>6.3.</strong> We will retain your personal data as follows:
                  </p>
                  
                  <ul className="list-disc list-inside space-y-2 ml-4">
                    <li><strong>(a)</strong> contact data will be retained for a minimum period of 3 years following the date of the most recent contact between you and us, and for a maximum period of 7 years following that date;</li>
                    <li><strong>(b)</strong> account data will be retained for a minimum period of 3 years following the date of closure of the relevant account, and for a maximum period of 7 years following that date;</li>
                    <li><strong>(c)</strong> transaction data will be retained for a minimum period of 3 years following the date of the transaction, and for a maximum period of 7 years following that date;</li>
                    <li><strong>(d)</strong> communication data will be retained for a minimum period of 3 years following the date of the communication in question, and for a maximum period of 7 years following that date;</li>
                    <li><strong>(e)</strong> usage data will be retained for 2 years following the date of collection;</li>
                    <li><strong>(f)</strong> access log data is automatically deleted after a few hours when the log file reaches a certain size;</li>
                    <li><strong>(g)</strong> notification data will be retained until you unsubscribe from the relevant notifications.</li>
                  </ul>
                  
                  <p>
                    <strong>6.4.</strong> Notwithstanding the other provisions of this Section 6, we may retain your personal data where such retention is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.
                  </p>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">7. Your rights</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>7.1.</strong> In this Section 7, we have listed the rights that you have under data protection law.
                  </p>
                  
                  <p>
                    <strong>7.2.</strong> Your principal rights under data protection law are:
                  </p>
                  
                  <ul className="list-disc list-inside space-y-2 ml-4">
                    <li><strong>(a)</strong> the right to access – you can ask for copies of your personal data;</li>
                    <li><strong>(b)</strong> the right to rectification – you can ask us to rectify inaccurate personal data and to complete incomplete personal data;</li>
                    <li><strong>(c)</strong> the right to erasure – you can ask us to erase your personal data;</li>
                    <li><strong>(d)</strong> the right to restrict processing – you can ask us to restrict the processing of your personal data;</li>
                    <li><strong>(e)</strong> the right to object to processing – you can object to the processing of your personal data;</li>
                    <li><strong>(f)</strong> the right to data portability – you can ask that we transfer your personal data to another organisation or to you;</li>
                    <li><strong>(g)</strong> the right to complain to a supervisory authority – you can complain about our processing of your personal data; and</li>
                    <li><strong>(h)</strong> the right to withdraw consent – to the extent that the legal basis of our processing of your personal data is consent, you can withdraw that consent.</li>
                  </ul>
                  
                  <p>
                    <strong>7.3.</strong> These rights are subject to certain limitations and exceptions. You can learn more about the rights of data subjects by visiting <a href="https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/" className="text-content-brand hover:underline">https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/</a>.
                  </p>
                  
                  <p>
                    <strong>7.4.</strong> You may exercise any of your rights in relation to your personal data by written notice to us, using the contact details set out below.
                  </p>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">8. About cookies</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>8.1.</strong> A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser and is stored by the browser. The identifier is then sent back to the server each time the browser requests a page from the server.
                  </p>
                  
                  <p>
                    <strong>8.2.</strong> Cookies may be either &quot;persistent&quot; cookies or &quot;session&quot; cookies: a persistent cookie will be stored by a web browser and will remain valid until its set expiry date, unless deleted by the user before the expiry date; a session cookie, on the other hand, will expire at the end of the user session, when the web browser is closed.
                  </p>
                  
                  <p>
                    <strong>8.3.</strong> Cookies may not contain any information that personally identifies a user, but personal data that we store about you may be linked to the information stored in and obtained from cookies.
                  </p>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">9. Cookies that we use</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>9.1.</strong> We use cookies for the following purposes:
                  </p>
                  
                  <ul className="list-disc list-inside space-y-2 ml-4">
                    <li><strong>(a)</strong> authentication and status – we use cookies to identify you when you visit our website and as you navigate our website, and to determine if you are logged into the website;</li>
                    <li><strong>(b)</strong> personalisation – we use cookies to store information about your preferences and to personalise the website for you;</li>
                    <li><strong>(c)</strong> security – we use cookies as an element of the security measures used to protect user accounts, including preventing fraudulent use of login credentials, and to protect our website and services generally;</li>
                    <li><strong>(d)</strong> advertising – we use cookies to help us to display advertisements that will be relevant to you;</li>
                    <li><strong>(e)</strong> analysis – we use cookies to help us to analyse the use and performance of our website and services; and</li>
                    <li><strong>(f)</strong> cookie consent – we use cookies to store your preferences in relation to the use of cookies more generally.</li>
                  </ul>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">10. Cookies used by our service providers</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>10.1.</strong> Our service providers use cookies and those cookies may be stored on your computer when you visit our website.
                  </p>
                  
                  <p>
                    <strong>10.2.</strong> We use Google Analytics to analyse the use of our website. Google Analytics gathers information about website use by means of cookies. The information gathered relating to our website is used to create reports about the use of our website. Google&apos;s privacy policy is available at: <a href="https://www.google.com/policies/privacy/" className="text-content-brand hover:underline">https://www.google.com/policies/privacy/</a>.
                  </p>
                  
                  <p className="ml-4">
                    We use Google Analytics to understand which pages are most popular and where visitors have come from. All data collected by Google Analytics is anonymous - we cannot identify you as an individual on the website. Google shows us the data in an aggregated way, meaning we know that a certain number of people visited a specific page, but we don&apos;t know who visited that page.
                  </p>
                  
                  <p className="ml-4">
                    Google Analytics sets cookies on your device to understand metrics such as return visits and what pages you visit during your session. All Google Analytics cookies begin with _ga, and none of them contain any personal data.
                  </p>
                  
                  <p>
                    <strong>10.3.</strong> We may use other analytics services from time to time, and these service providers may use cookies to gather information about your use of our website.
                  </p>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">11. Managing cookies</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>11.1.</strong> Most browsers allow you to refuse to accept cookies and to delete cookies. The methods for doing so vary from browser to browser, and from version to version. You can however obtain up-to-date information about blocking and deleting cookies via these links:
                  </p>
                  
                  <ul className="list-disc list-inside space-y-2 ml-4">
                    <li><strong>(a)</strong> <a href="https://support.google.com/chrome/answer/95647" className="text-content-brand hover:underline">https://support.google.com/chrome/answer/95647</a> (Chrome);</li>
                    <li><strong>(b)</strong> <a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences" className="text-content-brand hover:underline">https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences</a> (Firefox);</li>
                    <li><strong>(c)</strong> <a href="https://help.opera.com/en/latest/web-preferences/" className="text-content-brand hover:underline">https://help.opera.com/en/latest/web-preferences/</a> (Opera);</li>
                    <li><strong>(d)</strong> <a href="https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies" className="text-content-brand hover:underline">https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies</a> (Internet Explorer);</li>
                    <li><strong>(e)</strong> <a href="https://support.apple.com/en-gb/guide/safari/manage-cookies-and-website-data-sfri11471/mac" className="text-content-brand hover:underline">https://support.apple.com/en-gb/guide/safari/manage-cookies-and-website-data-sfri11471/mac</a> (Safari); and</li>
                    <li><strong>(f)</strong> <a href="https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy" className="text-content-brand hover:underline">https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy</a> (Edge).</li>
                  </ul>
                  
                  <p>
                    <strong>11.2.</strong> Blocking all cookies will have a negative impact upon the usability of many websites.
                  </p>
                  
                  <p>
                    <strong>11.3.</strong> If you block cookies, you will not be able to use all the features on our website.
                  </p>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">12. Amendments</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>12.1.</strong> We may update this policy from time to time by publishing a new version on our website.
                  </p>
                  
                  <p>
                    <strong>12.2.</strong> You should check this page occasionally to ensure you are happy with any changes to this policy.
                  </p>
                  
                  <p>
                    <strong>12.3.</strong> We may notify you of significant changes to this policy by email.
                  </p>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">13. Our details</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>13.1.</strong> This website is owned and operated by R3 Group Ltd.
                  </p>
                  
                  <p>
                    <strong>13.2.</strong> We are registered in England and Wales under registration number 05251479 and our registered office is at Maple House, Park West, Sealand Road, Chester, CH1 4RN.
                  </p>
                  
                  <p>
                    <strong>13.3.</strong> Our principal place of business is at Maple House, Park West, Sealand Road, Chester, CH1 4RN.
                  </p>
                  
                  <p>
                    <strong>13.4.</strong> You can contact us:
                  </p>
                  
                  <ul className="list-disc list-inside space-y-2 ml-4">
                    <li><strong>(a)</strong> by post, to the postal address given above;</li>
                    <li><strong>(b)</strong> using our website contact form;</li>
                    <li><strong>(c)</strong> by telephone, on <a href="tel:01244567560" className="text-content-brand hover:underline">01244 567 560</a>; or</li>
                    <li><strong>(d)</strong> by email, using <a href="mailto:studio@r3.agency" className="text-content-brand hover:underline">studio@r3.agency</a>.</li>
                  </ul>
                </div>
              </section>

              <section className="mb-8">
                <h2 className="title-4xl text-content-primary mb-4">14. Data protection officer</h2>
                
                <div className="space-y-4 text-content-muted">
                  <p>
                    <strong>14.1.</strong> Our data protection officer&apos;s contact details are: <a href="mailto:dpo@r3.agency" className="text-content-brand hover:underline">dpo@r3.agency</a>.
                  </p>
                </div>
              </section>
            </div>
          </div>
        </div>
      </main>

      <CMSFooter footerData={footerData} />
    </div>
  );
}